name: Build and Publish
on:
  # Trigger analysis when pushing in main or pull requests, and when creating
  # a pull request.
  push:
    branches: [main]
  pull_request:
      types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
